from . import word_embedding_avg_vector
from . import word_embedding_vectors
from . import similarity_between_contents_and_synopsis_sentence
from . import rouge_between_contents_and_synopsis_sentence
from . import embedding_matrix
from . import position_of_sentence
from . import is_serif
from . import is_include_person
from . import sentence_length
from . import opt_sentences
from . import active_ncodes